### ISSUE TITLE
Can't load plugin: Failed to get CreateInterface

### ISSUE THREAD

**Issue by CaptainZidgel** [laurirasanen/rampbugfix#10]
Tried to install on server (with latest Dhooks compiled for SM 1.10)
```
] rcon sm plugins load groundfix
L 04/05/2020 - 20:36:43: [SM] Exception reported: Failed to get CreateInterface
L 04/05/2020 - 20:36:43: [SM] Blaming: groundfix.smx
L 04/05/2020 - 20:36:43: [SM] Call stack trace:
L 04/05/2020 - 20:36:43: [SM]   [0] SetFailState
L 04/05/2020 - 20:36:43: [SM]   [1] Line 41, D:\Programming Projects\sourcemod\groundfix\scripting\groundfix.sp::OnPluginStart
[SM] Plugin groundfix.smx failed to load: Error detected in plugin startup (see error logs).
```

Dhooks included in the optional release with dhooks installed were not usable for 1.10 so I downloaded a release from here https://forums.alliedmods.net/showthread.php?t=320129 and dragged out the extension folder included, if that matters at all.

**Comment by laurirasanen** [comment]
The release version is compiled for 1.9, you'll need to compile from source with 1.10 compiler and includes.

**Comment by CaptainZidgel** [comment]
Great, thanks
